services:
  # Development Profile
  setup-development:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    profiles:
      - development
    # For development, we don't use "npm ci" because it removes the "node_modules" directory and re-installs all dependencies which makes the startup time longer.
    command: ["npm", "install"]
    volumes:
      - ./:/app

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development-api
    depends_on:
      setup-development:
        condition: service_completed_successfully
    profiles:
      - development
    ports:
      - "3000:3000"
    working_dir: /app/packages/api
    volumes:
      - ./:/app

  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development-fe
    depends_on:
      setup-development:
        condition: service_completed_successfully
    profiles:
      - development
    ports:
      - "3001:5173"
    working_dir: /app/packages/client
    volumes:
      - ./:/app

  # Production Profile
  api_production:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
      target: production
    profiles:
      - production
    ports:
      - "3000:3000"
    env_file:
      - ./packages/api/.env

  client_production:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
      target: production
    profiles:
      - production
    ports:
      - "3001:4173"
